#Import Library

In [1]:
import pandas as pd
import numpy as np

#Import Dataset

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/HazemNegm/GDG-Final-Project/968668ebe662b3d9f3ef228b7b6348d8cc60995c/Raw%20Data/global_tech_startups_2026.csv")

#Data Explaination

In [5]:
df.shape

(25000, 17)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Company_ID                  25000 non-null  object
 1   Domain                      25000 non-null  object
 2   Founding_Year               25000 non-null  int64
 3   Country                     25000 non-null  object
 4   City                        25000 non-null  object
 5   Funding_Stage               25000 non-null  object
 6   Total_Funding_USD_Millions  25000 non-null  float64
 7   Valuation_USD_Millions      25000 non-null  float64
 8   Revenue_ARR_Millions        25000 non-null  float64
 9   Monthly_Burn_Rate_Millions  25000 non-null  float64
 10  Runway_Months_2024          25000 non-null  float64
 11  Peak_Headcount_2023         25000 non-null  int64
 12  Layoffs_2024_2025           25000 non-null  int64
 13  Current_Headcount_2026      25000 non-null  int64
 14  Investor_Tier               25000 non-null  object
 15  AI_Adoption_Level           22408 non-null  object
 16  Acquisition_Status          25000 non-null  object
dtypes: float64(5), int64(4), object(8)
memory usage: 3.2+ MB

In [6]:
df.describe()

,Founding_Year,Total_Funding_USD_Millions,Valuation_USD_Millions,Revenue_ARR_Millions,Monthly_Burn_Rate_Millions,Runway_Months_2024,Peak_Headcount_2023,Layoffs_2024_2025,Current_Headcount_2026
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,2018.917400,59.631098,464.100121,33.300890,3.168847,12.189032,211.739920,31.563320,180.176600
std,2.811963,208.725699,1777.909318,139.243809,10.877553,10.099990,693.946443,175.987811,606.174385
min,2012.000000,0.000000,1.030000,0.050000,0.060000,0.000000,5.000000,0.000000,0.000000
25%,2017.000000,2.050000,28.997500,1.800000,0.430000,3.900000,30.000000,0.000000,22.000000
50%,2019.000000,8.465000,71.775000,4.825000,0.720000,10.600000,48.000000,0.000000,42.000000
75%,2021.000000,36.100000,267.795000,17.972500,2.240000,17.500000,154.000000,16.000000,119.000000
max,2025.000000,7867.390000,91692.420000,9021.530000,515.760000,89.600000,30086.000000,10280.000000,25657.000000

In [7]:
df.isnull().sum()

Company_ID                       0
Domain                           0
Founding_Year                    0
Country                          0
City                             0
Funding_Stage                    0
Total_Funding_USD_Millions       0
Valuation_USD_Millions           0
Revenue_ARR_Millions             0
Monthly_Burn_Rate_Millions       0
Runway_Months_2024               0
Peak_Headcount_2023              0
Layoffs_2024_2025                0
Current_Headcount_2026           0
Investor_Tier                    0
AI_Adoption_Level             2592
Acquisition_Status               0
dtype: int64

#Cleaning

##Fillna AI_Adoption_Level

In [8]:
df['AI_Adoption_Level'] = df['AI_Adoption_Level'].fillna('Unknown')

#Download CLeaned Data

In [10]:
from google.colab import files

# Save the cleaned dataframe to a CSV file
df.to_csv('cleaned_Data.csv', index=False)

# Download the file to your local system
files.download('cleaned_Data.csv')